#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
#cp "${HERE}/udev-rules-helper" /tmp/
# Try to run using sudo, if this does not work ask the user for password
#sudo -n -E -- "/tmp/udev-rules-helper" || pkexec "/tmp/udev-rules-helper"
#rm "/tmp/udev-rules-helper"
set -- "$@" "-M ${HERE}/qt-map.html"
exec "${HERE}/usr/bin/qt-dab "$@" 
