#!/bin/bash

HERE="$(dirname "$(readlink -f "${0}")")"

rmmod dvb_usb_rtl28xxu || true

cat > /tmp/10-rtl-sdr.rules <<\EOF
SUBSYSTEM=="usb", ATTRS{idVendor}=="0bda", ATTRS{idProduct}=="2838", GROUP="adm", MODE="0666", SYMLINK+="rtl_sdr"
EOF

mv /tmp/10-rtl-sdr.rules /etc/udev/rules.d/10-rtl-sdr.rules

cat < /tmp/66-mirics.rules <<\EOF
SUBSYSTEM=="usb",ENV{DEVTYPE}=="usb_device",ATTRS{idVendor}=="1df7",ATTRS{idProduct}=="3010",MODE:="0666"


mv /tmp/66-mirics.rules /etc/udev/rules.d/66-mirics.rules

udevadm control --reload-rules
udevadm trigger --attr-match=subsystem=usb
